import inquirer from 'inquirer';
import {
  isDirectoryEmpty,
  isValidProjectName,
  resolveTargetDir,
  sanitizeProjectName,
} from '../utils/validation.js';
import { DatabaseType, ProjectConfig } from '../types/index.js';

interface PromptAnswers {
  projectName: string;
  projectDescription: string;
  database: DatabaseType;
  docker: boolean;
  installDependencies: boolean;
}

export interface PromptOptions {
  database?: DatabaseType;
  docker?: boolean;
  installDependencies?: boolean;
  yes?: boolean;
}

const DEFAULTS = {
  projectName: 'my-fullstack-app',
  projectDescription: 'A full-stack application generated by create-stackforge-app.',
  database: 'postgresql' as DatabaseType,
  docker: true,
  installDependencies: true,
};

export async function promptProjectConfig(
  initialName?: string,
  cwd?: string,
  options: PromptOptions = {},
): Promise<ProjectConfig> {
  if (options.yes) {
    return buildNonInteractiveConfig(initialName, cwd, options);
  }

  const answers = await inquirer.prompt<PromptAnswers>([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: initialName || DEFAULTS.projectName,
      when: () => true,
      validate: async (input: string) => {
        const sanitized = sanitizeProjectName(input);
        const validation = isValidProjectName(sanitized);
        if (validation !== true) {
          return validation;
        }

        const targetDir = resolveTargetDir(sanitized, cwd);
        if (!(await isDirectoryEmpty(targetDir))) {
          return `Directory "${sanitized}" already exists and is not empty.`;
        }

        return true;
      },
      filter: (input: string) => sanitizeProjectName(input),
    },
    {
      type: 'input',
      name: 'projectDescription',
      message: 'Project description:',
      default: DEFAULTS.projectDescription,
    },
    {
      type: 'list',
      name: 'database',
      message: 'Choose a database:',
      choices: [
        { name: 'PostgreSQL (requires Docker or local Postgres)', value: 'postgresql' },
        { name: 'SQLite (lightweight, no extra services)', value: 'sqlite' },
      ],
      default: DEFAULTS.database,
      when: () => options.database === undefined,
    },
    {
      type: 'confirm',
      name: 'docker',
      message: 'Generate Docker support?',
      default: DEFAULTS.docker,
      when: () => options.docker === undefined,
    },
    {
      type: 'confirm',
      name: 'installDependencies',
      message: 'Install dependencies automatically? (requires pnpm)',
      default: DEFAULTS.installDependencies,
      when: () => options.installDependencies === undefined,
    },
  ]);

  const projectName = sanitizeProjectName(answers.projectName);

  return {
    projectName,
    projectDescription: answers.projectDescription,
    database: options.database ?? answers.database,
    docker: options.docker ?? answers.docker,
    installDependencies: options.installDependencies ?? answers.installDependencies,
    targetDir: resolveTargetDir(projectName, cwd),
  };
}

async function buildNonInteractiveConfig(
  initialName: string | undefined,
  cwd: string | undefined,
  options: PromptOptions,
): Promise<ProjectConfig> {
  const projectName = sanitizeProjectName(initialName || DEFAULTS.projectName);

  const validation = isValidProjectName(projectName);
  if (validation !== true) {
    throw new Error(validation);
  }

  const targetDir = resolveTargetDir(projectName, cwd);
  if (!(await isDirectoryEmpty(targetDir))) {
    throw new Error(`Directory "${projectName}" already exists and is not empty.`);
  }

  return {
    projectName,
    projectDescription: DEFAULTS.projectDescription,
    database: options.database ?? DEFAULTS.database,
    docker: options.docker ?? DEFAULTS.docker,
    installDependencies: options.installDependencies ?? DEFAULTS.installDependencies,
    targetDir,
  };
}
