import inquirer from 'inquirer';
import {
  isDirectoryEmpty,
  isValidProjectName,
  resolveTargetDir,
  sanitizeProjectName,
} from '../utils/validation.js';
import { DatabaseType, ProjectConfig } from '../types/index.js';

interface PromptAnswers {
  projectName: string;
  projectDescription: string;
  database: DatabaseType;
  docker: boolean;
  installDependencies: boolean;
}

export async function promptProjectConfig(
  initialName?: string,
  cwd?: string,
): Promise<ProjectConfig> {
  const answers = await inquirer.prompt<PromptAnswers>([
    {
      type: 'input',
      name: 'projectName',
      message: 'Project name:',
      default: initialName || 'my-fullstack-app',
      when: () => true,
      validate: async (input: string) => {
        const sanitized = sanitizeProjectName(input);
        const validation = isValidProjectName(sanitized);
        if (validation !== true) {
          return validation;
        }

        const targetDir = resolveTargetDir(sanitized, cwd);
        if (!(await isDirectoryEmpty(targetDir))) {
          return `Directory "${sanitized}" already exists and is not empty.`;
        }

        return true;
      },
      filter: (input: string) => sanitizeProjectName(input),
    },
    {
      type: 'input',
      name: 'projectDescription',
      message: 'Project description:',
      default: 'A full-stack application generated by create-stackforge-app.',
    },
    {
      type: 'list',
      name: 'database',
      message: 'Choose a database:',
      choices: [
        { name: 'PostgreSQL (requires Docker or local Postgres)', value: 'postgresql' },
        { name: 'SQLite (lightweight, no extra services)', value: 'sqlite' },
      ],
      default: 'postgresql',
    },
    {
      type: 'confirm',
      name: 'docker',
      message: 'Generate Docker support?',
      default: true,
    },
    {
      type: 'confirm',
      name: 'installDependencies',
      message: 'Install dependencies automatically? (requires pnpm)',
      default: true,
    },
  ]);

  const projectName = sanitizeProjectName(answers.projectName);

  return {
    projectName,
    projectDescription: answers.projectDescription,
    database: answers.database,
    docker: answers.docker,
    installDependencies: answers.installDependencies,
    targetDir: resolveTargetDir(projectName, cwd),
  };
}
